NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"
ACCOUNTS=[
"GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB”,
"GB4ZK5POZJJZJBFERNCXRQBEHTF3USTSSTRQVGGV72S5ZAVI2TG2KEBY"
]
[DOCUMENTATION]
ORG_NAME="DogRescue"
ORG_URL="https://alyii.github.io/"
ORG_LOGO="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/.well-known/LoveDog.png"
ORG_PHISICAL_ADDRESS="PANAMA, PANAMA"
ORG-OFFICIAL_EMAIL="Jw0Yk0@gmail.com
ORG_KEYBASE="Aging21"
ORG_GITHUB="AlYii"
ORG_DESCRIPTION="Helping Abused and Abandoned Dogs"
[[PRINCIPALS]]
name="Al Yi"
email="Jw0Yk0@gmail.com
keybase="aging21"
github="AlYii"
[[CURRENCIES]]
code="DogeDog"
issuer="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
is_asset_anchored=false
desc="LoveDog is a Charity Token making donations more accessible"
image="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/.well-known/LoveDog.png"
