# ----- LoveDog Token Used to donate Al Yi Charity Organization  <https://alyii.github.io> -----
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB",
"GB4ZK5POZJJZJBFERNCXRQBEHTF3USTSSTRQVGGV72S5ZAVI2TG2KEBY"
"GAVLQOSHJX6S6WY5WYZ6YCUXQ5LVIPIN3572O3U2LWPFGHY2V2XXRQW4"
]
SIGNING_KEY="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"

[DOCUMENTATION]
ORG_NAME="AlYi Charity Trust"
ORG_DBA="AlYi Charity"
ORG_URL="https://alyii.github.io"
ORG_LOGO="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/LoveDog128.png"
ORG_DESCRIPTION="LoveDog Token is used to rise fund to help abandonaded dog"
ORG_OFFICIAL_EMAIL="Jw0Yk0@gmail.com"

[[PRINCIPALS]]
name=Al Yi"
email="Jw0Yk0@gmail.com"

[[CURRENCIES]]
code="LoveDog"
issuer="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
display_decimals=7
name="Love Dog Token"
desc="LoveDog Token is used to rise fund to help abandonaded dog"
image="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/LoveDog128.png"
