ACCOUNTS=["GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"]
[DOCUMENTATION]
ORG_NAME="CHARITY FUNDING
[CURRENCIES]
code="LoveDog"
issuer="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
display_decimals=7
name="LoveDog"
desc="LoveDog is a token to send donations to charity organizations"
image="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/.well-known/LoveDog.png"
