ACCOUNTS=["GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"]
[DOCUMENTATION]
ORG_NAME="CHARITY FUNDING
ORG_URL="https://alyii.github.io/"
ORG_LOGO="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/LoveDog128.png"
ORG_DESCRIPTION="WE HELP ABANDONED ANIMALS TO LIVE A BETTER LIFE"
ORG_PHYSICAL_ADDRESS="PANAMA CITY PANAMA"
ORG_OFFICIAL_EMAIL="Jw0Yk0@gmail.com"
[CURRENCIES]
code="LoveDog"
issuer="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
display_decimals=7
name="LoveDog"
desc="LoveDog is a token to send donations to charity organizations"
image="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/.well-known/LoveDog.png"
