NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB" ] VERSION="2.0.0"
[DOCUMENTATION]
ORG_NAME="CHARITY FUNDING"
ORG_URL="https://alyii.github.io/"
ORG_LOGO="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/LoveDog128.png"
ORG_DESCRIPTION="HELP ABANDONED ANIMALS"
ORG_PHYSICAL_ADDRESS="PANAMA CITY PANAMA"
ORG_OFFICIAL_EMAIL="Jw0Yk0@gmail.com"
[[PRINCIPALS]]
name="Al Yi"
email="Jw0Yk0@gmail.com"
[[CURRENCIES]]
code="LoveDog"
issuer="GBWDOP7ONDKNJ222C3AS7KV74HGHIGZEM2AV3662HKJFSCUYJ7TQW2QB"
display_decimals=7
is_asset_anchored=false
desc="LoveDog is a token to send donations to charity fund"
image="https://raw.githubusercontent.com/AlYii/AlYii.github.io/main/LoveDog128.png"
